### ISSUE TITLE
I got a question for ya

### ISSUE THREAD

**Issue by BlaisinX** [HardWare68/Programming-Thing#54]
Two trains, Train A and Train B, simultaneously depart Station A and Station B. Station A and Station B are 252.5 miles apart from each other. Train A is moving at 124.7mph towards Station B, and Train B is moving at 253.5mph towards Station A. If both trains departed at 10:00AM and it is now 10:08, how much longer until both trains pass each other?

**Comment by HardWare68** [comment]
To solve this problem, we can use dA/dt and dB/dt to represent the speeds of Train A and B with respect to time, respectively.

dA/dt = 124.7
dB/dt = 253.5

We also know the distance between the two stations, which I will denote as A and B, is 252.5. We can write this as B - 252.5 = A; if you subtracted 252.5 miles from b, you would end up in a's position. I know this isn't exactly correct, but yolo. Taking the derivative of that equation, with respect to time, will result in us getting

dB/dt = dA/dt.
(253.5) = (124.7)

Since this evaluates to a false, we can safely say that the trains never pass each other.

**Comment by BlaisinX** [comment]
the answer is 32 minutes dumbass

**Comment by HardWare68** [comment]
Not quite. My question to you is that Train B is moving at 253.5 mph towards Station A. Station A is 252.5 miles away. Therefore, it would reach Station A in under a minute. How the hell does that make sense?

**Comment by BlaisinX** [comment]
it's miles per hour not miles per minute dumbass

**Comment by HardWare68** [comment]
We have established the following information:
Train B is moving at 253.5 mph.
Station A is 252.5 miles away.

253.5 miles per hour/252.5 miles = 1 hour

Now, I give you this question. Put 1 hour into your microwave. You'd most likely press the buttons 6, 0, 0, 0 to get one hour. Now, I just lost my train of thought, but in the end, one hour does not equal one hour, and if we continue with that line of logic, then it reveals that yo mama is so fat, she is the distance between Station A and Station B.

**Comment by ptechofficial** [comment]
Let's say they meet after time 't' hours.
Now we have an equation,
252.2 = 253.5(t) + 124.7(t)

we get t = 0.6668 hours or 40 minutes
so they'll meet at 10:40 am
Now it is 32 minutes after 10:08.
Thus the answer is 32 minutes.
